package com.aptech.a5;

import com.aptech.a5.repository.RepositoryException;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * The database, kept out of everybody's way. GIVEN — do not change it.
 *
 * <p>Schema creation was Assignment A4. Here it is furniture, so that R1–R8 can be about design
 * rather than about {@code CREATE TABLE}. What is worth reading is the two things it demonstrates:
 *
 * <ul>
 *   <li>{@link #reset} drops and recreates the tables, so the same program always prints the same
 *       numbers — an assignment you cannot reproduce is an assignment you cannot mark;</li>
 *   <li>{@link #open} turns the checked {@link SQLException} into the unchecked
 *       {@link RepositoryException} at the boundary. That single {@code catch} is why
 *       {@code StudentRepository} can declare no checked exception anywhere.</li>
 * </ul>
 */
public final class Db {

    /** The real registry: a file, so it is still there next time. */
    public static final String URL = "jdbc:h2:./data/registry";

    /** A throwaway database that lives only as long as the JVM. SelfCheck uses this one. */
    public static final String MEM_URL = "jdbc:h2:mem:a5check;DB_CLOSE_DELAY=-1";

    private Db() {
    }

    public static Connection open() {
        return open(URL);
    }

    /** Never hand this Connection to a caller that outlives the method — close it where you opened it. */
    public static Connection open(String url) {
        try {
            return DriverManager.getConnection(url, "sa", "");
        } catch (SQLException e) {
            throw new RepositoryException("cannot open " + url + ": " + e.getMessage(), e);
        }
    }

    public static void reset() {
        reset(URL);
    }

    /**
     * Drops both tables, recreates them, and seeds 4 courses and 8 students.
     *
     * <p>Every run of every program in this assignment starts here, which is why the reports are
     * reproducible to the byte. The identity counter restarts because the table is new, so
     * Ada is always id 1.
     */
    public static void reset(String url) {
        try (Connection c = open(url); Statement st = c.createStatement()) {
            st.execute("DROP TABLE IF EXISTS students");
            st.execute("DROP TABLE IF EXISTS courses");
            st.execute("CREATE TABLE courses ("
                    + " id INT PRIMARY KEY,"
                    + " title VARCHAR(80) NOT NULL,"
                    + " credits INT NOT NULL,"
                    + " fee DECIMAL(9,2) NOT NULL)");
            st.execute("CREATE TABLE students ("
                    + " id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " name VARCHAR(100) NOT NULL,"
                    + " email VARCHAR(150) NOT NULL UNIQUE,"
                    + " course_id INT REFERENCES courses(id),"
                    + " mark DECIMAL(5,2),"
                    + " active BOOLEAN NOT NULL DEFAULT TRUE)");
            st.executeUpdate("INSERT INTO courses (id, title, credits, fee) VALUES"
                    + " (1, 'Java Programming', 12, 450.00),"
                    + " (2, 'Database Fundamentals', 10, 380.00),"
                    + " (3, 'Web Development', 8, 320.00),"
                    + " (4, 'Software Engineering', 14, 520.00)");
            st.executeUpdate("INSERT INTO students (name, email, course_id, mark, active) VALUES"
                    + " ('Ada Lovelace',      'ada@example.com',      1, 88.50, TRUE),"
                    + " ('Grace Hopper',      'grace@example.com',    1, 91.00, TRUE),"
                    + " ('Alan Turing',       'alan@example.com',     2, 76.25, TRUE),"
                    + " ('Margaret Hamilton', 'margaret@example.com', 1, 70.00, TRUE),"
                    + " ('Katherine Johnson', 'katherine@example.com',3, 95.00, TRUE),"
                    + " ('Linus Torvalds',    'linus@example.com',    2, 64.00, FALSE),"
                    + " ('Barbara Liskov',    'barbara@example.com',  4, 82.75, TRUE),"
                    + " ('Dennis Ritchie',    'dennis@example.com',   3, 58.00, TRUE)");
        } catch (SQLException e) {
            throw new RepositoryException("cannot reset the registry: " + e.getMessage(), e);
        }
    }

    /** The horizontal rules the reports use, so every program prints the same shape. */
    public static String rule(String title) {
        return "\n=== " + title + " " + "=".repeat(Math.max(0, 60 - title.length()));
    }
}
