package com.aptech.s08.practice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.aptech.s08.Db;

/**
 * PRACTICE 1 (Easy) — prove that a rollback undoes a write, and a commit does not.
 *
 * <p>Write the smallest program that shows the difference. Insert a row with auto-commit off,
 * roll back, and check it is gone; insert another, commit, and check it is still there. Nothing
 * here is new — it is E01 and E02 with the training wheels off.
 *
 * <p><strong>Expected output:</strong> the first row is gone after the rollback, the second
 * survives the commit.
 */
public class P1_RollbackOrCommit {

    public static void main(String[] args) throws SQLException {
        System.out.println("P1 - a rollback undoes, a commit keeps");

        try (Connection c = Db.open()) {

            try (Statement st = c.createStatement()) {
                st.execute("DROP TABLE IF EXISTS p1_demo");
                st.execute("CREATE TABLE p1_demo (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                         + " label VARCHAR(40))");
            }

            // ---- rollback ----
            c.setAutoCommit(false);
            try (PreparedStatement ps = c.prepareStatement("INSERT INTO p1_demo (label) VALUES (?)")) {
                ps.setString(1, "should-vanish");
                ps.executeUpdate();
            }
            System.out.println("  inserted 'should-vanish', then rollback()...");
            c.rollback();
            System.out.println("  rows now: " + count(c) + "   <- the rollback undid it");

            // ---- commit ----
            try (PreparedStatement ps = c.prepareStatement("INSERT INTO p1_demo (label) VALUES (?)")) {
                ps.setString(1, "should-stay");
                ps.executeUpdate();
            }
            System.out.println("  inserted 'should-stay', then commit()...");
            c.commit();
            System.out.println("  rows now: " + count(c) + "   <- the commit kept it");

            c.setAutoCommit(true);
            try (Statement st = c.createStatement();
                 ResultSet rs = st.executeQuery("SELECT label FROM p1_demo")) {
                while (rs.next()) System.out.println("    in the table: " + rs.getString("label"));
            }

            try (Statement st = c.createStatement()) {
                st.execute("DROP TABLE p1_demo");
            }
        }

        System.out.println("\nrollback() rewinds to the last commit. commit() makes it permanent.");
    }

    private static int count(Connection c) throws SQLException {
        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM p1_demo")) {
            rs.next();
            return rs.getInt(1);
        }
    }
}
