-- ============================================================================
--  Session 8 — the Student Registry, extended for Advanced JDBC.
--
--  Session 7 gave the registry a real table. This adds the two tables that make
--  TRANSACTIONS matter: enrolling a student and taking their fee are two writes
--  that must succeed together, or neither must happen.
--
--  Written for H2. The lines that differ on MySQL are noted in the H2 & MySQL
--  guide, Part D:
--     GENERATED BY DEFAULT AS IDENTITY  ->  AUTO_INCREMENT
--     BOOLEAN                           ->  TINYINT(1)
--     TIMESTAMP                         ->  DATETIME
-- ============================================================================

-- ---- from Session 7 ---------------------------------------------------------

CREATE TABLE courses (
    id      INT           PRIMARY KEY,
    title   VARCHAR(80)   NOT NULL,
    credits INT           NOT NULL,
    fee     DECIMAL(9,2)  NOT NULL
);

CREATE TABLE students (
    id        INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100)  NOT NULL,
    email     VARCHAR(150)  UNIQUE,
    course_id INT,
    mark      DECIMAL(5,2),
    active    BOOLEAN       DEFAULT TRUE,
    joined    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_course FOREIGN KEY (course_id) REFERENCES courses(id)
);

-- ---- new in Session 8 -------------------------------------------------------

-- A student on a course. `paid` tracks whether the fee has been settled.
CREATE TABLE enrolments (
    id         INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT           NOT NULL,
    course_id  INT           NOT NULL,
    paid       BOOLEAN       DEFAULT FALSE,
    enrolled_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_enrol_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_enrol_course  FOREIGN KEY (course_id)  REFERENCES courses(id)
);

-- Money received against an enrolment. The sum of these is what the student owes.
-- The enrolments.paid flag and the rows here MUST agree - keeping them in step is
-- exactly what a transaction is for.
CREATE TABLE fee_payments (
    id           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrolment_id INT          NOT NULL,
    amount       DECIMAL(9,2) NOT NULL,
    paid_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_enrolment FOREIGN KEY (enrolment_id) REFERENCES enrolments(id)
);
