package com.aptech.a4;

import java.sql.Connection;
import java.util.List;

/**
 * Assignment A4 — Student Registry on H2.   <<< THIS IS THE FILE YOU COMPLETE >>>
 *
 * Scenario: the Student Registry you have kept in memory since Session 1 now needs to
 * survive. You are giving it a real database: an embedded H2 file, reached through JDBC,
 * that is still there when the program is closed and opened again.
 *
 * Replace every TODO with real code. Run SelfCheck after each requirement (aim: all PASS).
 * Then run Main to watch the registry being used.
 *
 * Rules for this assignment:
 *   - Every value in a SQL statement goes through a ? . No string concatenation, ever.
 *     (SelfCheck tries an injection on your search method — it must return nothing.)
 *   - Every Connection, Statement, PreparedStatement and ResultSet is closed on every path.
 *     Use try-with-resources; do not write a finally block by hand.
 *   - Read columns by LABEL, not by number.
 *   - Nothing is left open when a method returns.
 *
 * Author: YOUR NAME HERE
 */
public final class StudentRegistry {

    /** One student, as the rest of the program sees one. No JDBC types leak past this record. */
    public record Student(int id, String name, String email, int courseId, double mark) {
        @Override public String toString() {
            return String.format("%-4d %-20s %-24s course %-3d %6.2f", id, name, email, courseId, mark);
        }
    }

    private final String url;

    public StudentRegistry(String url) {
        this.url = url;
    }

    /**
     * Opens a new connection. Every method below calls this, uses try-with-resources,
     * and lets it close — do not hand a Connection out to a caller.
     */
    private Connection connect() throws Exception {
        // TODO A — return DriverManager.getConnection(url, "sa", "")
        throw new UnsupportedOperationException("A: connect() not implemented");
    }

    /**
     * R1 — Creates the two tables if they are not already there, and does nothing if they are.
     * courses(id, title, credits)  and  students(id, name, email, course_id, mark).
     *
     * Use CREATE TABLE IF NOT EXISTS so calling this twice is safe.
     * id is an identity column: INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY.
     */
    public void createSchema() throws Exception {
        // TODO R1
        throw new UnsupportedOperationException("R1: createSchema() not implemented");
    }

    /**
     * R2 — Inserts a student and returns the id the DATABASE assigned.
     * Use Statement.RETURN_GENERATED_KEYS and getGeneratedKeys().
     */
    public int insert(String name, String email, int courseId, double mark) throws Exception {
        // TODO R2
        throw new UnsupportedOperationException("R2: insert() not implemented");
    }

    /**
     * R3 — Returns the student with this id, or null if there is no such row.
     * Absence is normal: return null, do not throw.
     */
    public Student findById(int id) throws Exception {
        // TODO R3
        throw new UnsupportedOperationException("R3: findById() not implemented");
    }

    /**
     * R4 — Returns every student whose name CONTAINS the given text, ordered by name.
     * Use LIKE with a parameterized query. The match text becomes the value, never the SQL,
     * so a search for  ' OR '1'='1  must come back empty rather than returning the table.
     *
     * Hint: put the % wildcards around the VALUE — ps.setString(1, "%" + text + "%") —
     * not into the SQL string.
     */
    public List<Student> searchByName(String text) throws Exception {
        // TODO R4
        throw new UnsupportedOperationException("R4: searchByName() not implemented");
    }

    /**
     * R5 — Sets a student's mark. Returns the number of rows changed (1, or 0 if no such id).
     */
    public int updateMark(int id, double mark) throws Exception {
        // TODO R5
        throw new UnsupportedOperationException("R5: updateMark() not implemented");
    }

    /**
     * R6 — Deletes a student. Returns the number of rows removed (1, or 0 if no such id).
     */
    public int delete(int id) throws Exception {
        // TODO R6
        throw new UnsupportedOperationException("R6: delete() not implemented");
    }

    /**
     * R7 — Returns how many students are in the table.
     */
    public int count() throws Exception {
        // TODO R7
        throw new UnsupportedOperationException("R7: count() not implemented");
    }

    /**
     * R8 — Returns the COLUMN NAMES of the students table, read from the database's own
     * metadata — not from a hard-coded list.
     *
     * Hint: connection.getMetaData().getColumns(null, null, "STUDENTS", null),
     * then collect COLUMN_NAME in order.
     */
    public List<String> columnNames() throws Exception {
        // TODO R8
        throw new UnsupportedOperationException("R8: columnNames() not implemented");
    }
}
