package com.aptech.s08;

import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;

/**
 * E04 — batch updates: many statements, one round trip.
 *
 * <p>Every {@code executeUpdate()} is a round trip to the database. Inserting two thousand rows
 * one at a time is two thousand trips; {@code addBatch()} collects the statements and
 * {@code executeBatch()} sends them together. The saving is real and it is why bulk loading
 * exists as a technique.
 *
 * <p>The second half is the part people forget: a batch can <em>partly</em> fail.
 * {@code BatchUpdateException} carries a count of how many succeeded before the failure — so a
 * batch <strong>on its own</strong> leaves the database half-loaded. That is the connection back
 * to E01, and it is why a batch and a transaction belong together. The example proves both
 * halves: the same failing batch twice, once without a transaction and once with.
 */
public class E04_BatchUpdates {

    private static final int ROWS = 2000;

    public static void main(String[] args) throws SQLException {
        System.out.println("E04 - batch updates: many statements, one round trip");

        try (Connection c = Db.open()) {

            // Make a scratch table so we never disturb the seeded data.
            try (Statement st = c.createStatement()) {
                st.execute("DROP TABLE IF EXISTS batch_demo");
                st.execute("CREATE TABLE batch_demo (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                         + " label VARCHAR(40), amount DECIMAL(9,2))");
            }

            // ---- timing: three ways to insert the same 2000 rows ----
            // Each mode is run twice and the faster run is reported: a single run is noisy on a
            // shared machine. The counts are what matter, and they are the same every time.
            String insert = "INSERT INTO batch_demo (label, amount) VALUES (?, ?)";

            long oneAtATime = bestOfTwo(c, () -> insertOneAtATime(c, insert));
            System.out.println(Db.rule("1. one statement at a time, auto-commit on"));
            System.out.println("  2000 INSERTs, each sent separately and each its own commit");
            System.out.println("  took " + oneAtATime + " ms");

            long batched = bestOfTwo(c, () -> insertBatched(c, insert, true));
            System.out.println(Db.rule("2. batched, auto-commit still on"));
            System.out.println("  one executeBatch() carrying 2000 statements - but still 2000 commits");
            System.out.println("  took " + batched + " ms");

            long batchedInTx = bestOfTwo(c, () -> insertBatched(c, insert, false));
            System.out.println(Db.rule("3. batched, inside ONE transaction"));
            System.out.println("  one executeBatch() carrying 2000 statements - and ONE commit");
            System.out.println("  took " + batchedInTx + " ms");

            System.out.println(Db.rule("what actually changed - these numbers do not move"));
            System.out.println("  mode                            calls to the database   commits");
            System.out.printf("  1. one at a time                        %5d           %5d%n", ROWS, ROWS);
            System.out.printf("  2. batched, auto-commit on              %5d           %5d%n", 1, ROWS);
            System.out.printf("  3. batched, one transaction             %5d           %5d%n", 1, 1);
            System.out.println();
            System.out.println("  The milliseconds above wobble between runs. This is an EMBEDDED");
            System.out.println("  database in the same process: there is no network to cross, so the");
            System.out.println("  saving is only parse-and-commit work, and it competes with whatever");
            System.out.println("  else the machine is doing. Do not read a precise ratio out of it.");
            System.out.println();
            System.out.println("  The counts never wobble, and they are why bulk loading exists. Put");
            System.out.println("  the database on another machine and every one of those 2000 calls");
            System.out.println("  becomes a message out and a reply back; every one of those 2000");
            System.out.println("  commits becomes a flush to the remote disk. Fewer of both is faster,");
            System.out.println("  and 2000 commits becoming 1 is the change that usually matters most.");
            System.out.println("  Notice that this is a TRANSACTION win, not a batch win - which is");
            System.out.println("  exactly the subject of today's session.");

            // Empty the scratch table, so the next section starts from a clean count.
            try (Statement st = c.createStatement()) {
                st.executeUpdate("DELETE FROM batch_demo");
            }

            // ---- a batch that partly fails: WITHOUT a transaction ----
            System.out.println(Db.rule("a batch that fails halfway - no transaction"));
            int before = count(c, "batch_demo");
            try {
                batchWithAFailure(c, false);
            } catch (BatchUpdateException e) {
                System.out.println("  BatchUpdateException caught");
                System.out.println("  updateCounts() -> " + Arrays.toString(e.getUpdateCounts())
                        + "   (one entry per queued statement)");
            }
            System.out.println("  rows before: " + before + ", after: " + count(c, "batch_demo")
                    + "   <-- the three good ones STAYED. A batch is not a transaction.");

            // ---- the same batch, INSIDE a transaction ----
            System.out.println(Db.rule("the same batch, inside a transaction"));
            int beforeTx = count(c, "batch_demo");
            try {
                batchWithAFailure(c, true);
            } catch (BatchUpdateException e) {
                System.out.println("  BatchUpdateException caught, and rolled back");
                System.out.println("  updateCounts() -> " + Arrays.toString(e.getUpdateCounts()));
            }
            System.out.println("  rows before: " + beforeTx + ", after: " + count(c, "batch_demo")
                    + "   <-- nothing left behind");

            System.out.println(Db.rule("the rule that follows"));
            System.out.println("  addBatch()/executeBatch() is about SPEED, not safety.");
            System.out.println("  If a half-loaded table is unacceptable, put the batch inside a");
            System.out.println("  transaction: setAutoCommit(false), executeBatch(), then commit() -");
            System.out.println("  and rollback() in the catch. Speed and safety are separate tools.");

            // tidy up
            try (Statement st = c.createStatement()) {
                st.execute("DROP TABLE batch_demo");
            }
        }

        System.out.println("\nOne round trip for many statements. Wrap it in a transaction if it must be all-or-nothing.");
    }

    // ------------------------------------------------------------------ timing

    /** A piece of work whose elapsed time we want to measure. */
    @FunctionalInterface
    private interface Timed {
        void run() throws SQLException;
    }

    /** Runs the same work twice, emptying the scratch table first, and keeps the faster time. */
    private static long bestOfTwo(Connection c, Timed work) throws SQLException {
        long best = Long.MAX_VALUE;
        for (int attempt = 0; attempt < 2; attempt++) {
            try (Statement st = c.createStatement()) {
                st.executeUpdate("DELETE FROM batch_demo");
            }
            long t0 = System.currentTimeMillis();
            work.run();
            best = Math.min(best, System.currentTimeMillis() - t0);
        }
        return best;
    }

    /** Inserts ROWS rows, one executeUpdate() at a time, auto-commit on. */
    private static void insertOneAtATime(Connection c, String insert) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement(insert)) {
            for (int i = 1; i <= ROWS; i++) {
                ps.setString(1, "single-" + i);
                ps.setDouble(2, i);
                ps.executeUpdate();
            }
        }
    }

    /**
     * The same ROWS rows queued with addBatch() and sent with one executeBatch().
     *
     * @param autoCommit true  — each insert commits as it runs (mode 2)
     *                   false — one commit for the whole batch (mode 3)
     */
    private static void insertBatched(Connection c, String insert, boolean autoCommit) throws SQLException {
        if (!autoCommit) c.setAutoCommit(false);
        try (PreparedStatement ps = c.prepareStatement(insert)) {
            for (int i = 1; i <= ROWS; i++) {
                ps.setString(1, "batched-" + i);
                ps.setDouble(2, i);
                ps.addBatch();                 // queue it
            }
            ps.executeBatch();                 // send them all
            if (!autoCommit) c.commit();       // one commit for 2000 inserts
        } finally {
            if (!autoCommit) c.setAutoCommit(true);
        }
    }

    // ------------------------------------------------------- the failing batch

    /**
     * Queues three good rows then a bad one, and sends the batch.
     *
     * <p>The bad row's label is longer than the column, so the database rejects it — and by then
     * the first three have already run. With {@code useTransaction} false, that leaves three rows
     * behind. With it true, the catch rolls them back as well.
     */
    private static void batchWithAFailure(Connection c, boolean useTransaction) throws SQLException {
        if (useTransaction) c.setAutoCommit(false);
        String sql = "INSERT INTO batch_demo (label, amount) VALUES (?, ?)";
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, "ok-1"); ps.setDouble(2, 1); ps.addBatch();
            ps.setString(1, "ok-2"); ps.setDouble(2, 2); ps.addBatch();
            ps.setString(1, "ok-3"); ps.setDouble(2, 3); ps.addBatch();
            // 60 characters into a VARCHAR(40): the database refuses this one
            ps.setString(1, "this-label-is-far-too-long-for-the-column-and-will-be-rejected");
            ps.setDouble(2, 4);
            ps.addBatch();

            ps.executeBatch();
            if (useTransaction) c.commit();
        } catch (BatchUpdateException e) {
            if (useTransaction) c.rollback();
            throw e;
        } finally {
            if (useTransaction) c.setAutoCommit(true);
        }
    }

    private static int count(Connection c, String table) throws SQLException {
        try (Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM " + table)) {
            rs.next();
            return rs.getInt(1);
        }
    }
}
