package com.aptech.s07.practice;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * PRACTICE 1 (Easy) — the six steps, once, with no help.
 *
 * <p>Write the smallest complete JDBC program: connect to a database that exists only in
 * memory, create a table, put one row in, and read it back. Nothing here is new — it is E01
 * with the training wheels off.
 *
 * <p>Then notice what you did NOT have to write: no driver class name, no <code>Class.forName</code>,
 * no <code>finally</code> block. Those three omissions are the whole of JDBC since Java 6.
 *
 * <p><strong>Expected output:</strong> the row you inserted, printed back to you.
 */
public class P1_ConnectAndCreate {

    public static void main(String[] args) throws SQLException {

        System.out.println("P1 - connect, create, insert, read back");

        // An in-memory database: exists only while this program runs. DB_CLOSE_DELAY=-1
        // keeps it alive until the JVM exits, so the second connection below still sees it.
        String url = "jdbc:h2:mem:p1;DB_CLOSE_DELAY=-1";

        // ---- create and fill (steps 2-4, with step 6 handled by try-with-resources) ----
        try (Connection c = DriverManager.getConnection(url, "sa", "");
             Statement st = c.createStatement()) {

            st.execute("CREATE TABLE books ("
                     + " id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                     + " title  VARCHAR(120) NOT NULL,"
                     + " author VARCHAR(80))");

            st.executeUpdate("INSERT INTO books (title, author) VALUES ('Effective Java', 'Bloch')");
            System.out.println("  created the table and inserted one row");
        }
        // the connection is closed here - and the database is still there, because
        // DB_CLOSE_DELAY=-1 keeps the in-memory database until the JVM exits.

        // ---- read it back in a SECOND connection (proving the data outlived the first) ----
        try (Connection c = DriverManager.getConnection(url, "sa", "");
             Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT id, title, author FROM books")) {

            while (rs.next()) {
                System.out.printf("  read back: id=%d  \"%s\" by %s%n",
                        rs.getInt("id"), rs.getString("title"), rs.getString("author"));
            }
        }

        System.out.println("\nNo Class.forName, no finally, and the row survived the close.");
    }

    /**
     * The same insert, done the way you would in real code: a PreparedStatement, so the
     * values cannot change the SQL. Included here as the shape to copy from Step 5 onward.
     */
    @SuppressWarnings("unused")
    private static void insertTheRightWay(Connection c, String title, String author) throws SQLException {
        String sql = "INSERT INTO books (title, author) VALUES (?, ?)";
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, title);
            ps.setString(2, author);
            ps.executeUpdate();
        }
    }
}
