-- ============================================================================
--  Session 7 — the Student Registry schema.
--
--  This is the same registry you have been keeping in memory since Session 1,
--  now given a real table of its own. Two tables, one foreign key — enough to
--  show a join, and enough for DatabaseMetaData to have something to describe.
--
--  Written for H2 (the embedded database this course uses). Every line here is
--  also valid MySQL except:
--     GENERATED BY DEFAULT AS IDENTITY  ->  AUTO_INCREMENT
--     BOOLEAN                           ->  TINYINT(1)
--  See the H2 & MySQL guide, Part D, and E07_MySqlComparison.java.
-- ============================================================================

CREATE TABLE courses (
    id      INT           PRIMARY KEY,
    title   VARCHAR(80)   NOT NULL,
    credits INT           NOT NULL
);

CREATE TABLE students (
    id        INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100)  NOT NULL,
    email     VARCHAR(150)  UNIQUE,
    course_id INT,
    mark      DECIMAL(5,2),
    active    BOOLEAN       DEFAULT TRUE,
    joined    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_course FOREIGN KEY (course_id) REFERENCES courses(id)
);
